# Matrizes e Vetores

In [1]:
import numpy as np

In [4]:
# Vetores unidimensionais
vetor1 = np.array(['Carro','Casa','Predio','Moto'])

In [5]:
vetor1

array(['Carro', 'Casa', 'Predio', 'Moto'], dtype='<U6')

In [7]:
# Vetores Bidimensionais
vetor2 = np.array([['Moto','Carro','Caminhão'],['Predio','Casa','Trailer']])

In [8]:
vetor2

array([['Moto', 'Carro', 'Caminhão'],
       ['Predio', 'Casa', 'Trailer']], dtype='<U8')

In [10]:
# Verificando Tamanho do vetor
print(vetor1.shape)
print(vetor2.shape)

(4,)
(2, 3)


In [14]:
# Verificando Dimensão do vetor
print("Vetor 1:", vetor1.ndim)
print("Vetor 2:", vetor2.ndim)

Vetor 1: 1
Vetor 2: 2


# Metodos de criação

## numpy.arange - Criar um vetor com n posições

In [33]:
arange1 = np.arange(20)
arange1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

## usando arange start/end/skip - de start a end de skip em skip


In [34]:
# Usando start/end/skip - de start a end de skip em skip
arange2 = np.arange(0, 50, 10)
arange2

array([ 0, 10, 20, 30, 40])

## numpy.linspace(start/end/amount) - de start a end aleatorio até obter amount valores


In [35]:
linspace1 = np.linspace(0, 10, 20)
linspace1

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [21]:
linspace2 = np.linspace(0,10,5)
linspace2

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

## numpy.zeros - cria uma matriz com todas as casas com valor ZERO


In [36]:
zeros1 = np.zeros((10, 10))
zeros1

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [37]:
zeros2 = np.zeros((5, 5))
zeros2

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

## numpy.ones - cria uma matriz com todas as casas com valor UM

In [38]:
ones1 = np.ones((10, 10))
ones1

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [39]:
ones2 = np.ones((5, 5))
ones2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## numpy.eye - cria uma matriz do tipo Identity

In [40]:
eye1 = np.eye(10)
eye1

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [41]:
eye2 = np.eye(5)
eye2

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## numpy.diag - produz o mesmo resultado, porem definimos os numeros das diagonais

In [31]:
diag1 = np.diag((2,4,6,8,10,12,14,16,18,20))
diag1

array([[ 2,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  4,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  6,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  8,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 10,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0, 12,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0, 14,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 16,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0, 18,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0, 20]])

In [48]:
diag2 = np.diag((2,4,6,8,10))
diag2

array([[ 2,  0,  0,  0,  0],
       [ 0,  4,  0,  0,  0],
       [ 0,  0,  6,  0,  0],
       [ 0,  0,  0,  8,  0],
       [ 0,  0,  0,  0, 10]])

## numpy.empty - produz uma matriz vazia

In [74]:
empty1 = np.empty([3,3])
empty1

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

## numpy.tile - multiplica os valores do array em vertical e horizontal

In [78]:
# cada array repete n vezes em cada linha
tile1 = np.tile(np.array([[1, 2], [3, 4], [5, 6]]), 3)
tile1

array([[1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4],
       [5, 6, 5, 6, 5, 6]])

In [79]:
#Num de vezes do array na vertical , num de vezes array na horizontal
tile2 = np.tile(np.array([[1, 2], [3, 4]]), (3,6)) 
tile2

array([[1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4, 3, 4, 3, 4, 3, 4],
       [1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4, 3, 4, 3, 4, 3, 4],
       [1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4, 3, 4, 3, 4, 3, 4]])